export default {
  profile: {
    name: "Max Yankov",
    headline: "Product engineer for agent-related software",
    email: "golergka@gmail.com",
    github: "https://github.com/golergka",
    linkedin: "https://www.linkedin.com/in/maxyankov/",
    twitter: "https://x.com/GolerGkA",
    stackoverflow: "https://stackoverflow.com/users/312725/max-yankov",
    summary:
      "I build products around AI agents: the interfaces, tools, infrastructure, and safety systems that make them useful. My background spans full-stack and native engineering, developer tools, databases, games, and technical leadership.",
  },
  filters: [
    { id: "career-moves", label: "Career moves", kind: "faq" },
    { id: "contractor", label: "Contractor", kind: "faq" },
    { id: "agents", label: "AI & agents" },
    { id: "evals", label: "LLM evaluation", parent: "agents" },
    { id: "autonomous-development", label: "Autonomous development", parent: "agents" },
    { id: "pydantic-ai", label: "Pydantic AI", parent: "agents" },
    { id: "llamaindex", label: "LlamaIndex", parent: "agents" },
    { id: "langchain", label: "LangChain", parent: "agents" },
    { id: "agent-harness", label: "Agent harness", parent: "agents" },
    { id: "vercel-ai-sdk", label: "Vercel AI SDK", parent: "agents" },
    { id: "llms", label: "LLMs", parent: "agents" },
    { id: "livekit", label: "LiveKit / voice AI", parent: "agents" },
    { id: "braintrust", label: "Braintrust", parent: "agents" },
    { id: "developer-tools", label: "Developer tools" },
    { id: "ides", label: "IDEs", parent: "developer-tools" },
    { id: "type-systems", label: "Type systems", parent: "developer-tools" },
    { id: "product", label: "Product engineering" },
    { id: "frontend", label: "Frontend", parent: "product" },
    { id: "backend", label: "Backend", parent: "product" },
    { id: "native", label: "Native apps", parent: "product" },
    { id: "python", label: "Python", parent: "product" },
    { id: "typescript", label: "TypeScript", parent: "product" },
    { id: "node-bun", label: "Node.js / Bun", parent: "product" },
    { id: "react", label: "React / Preact", parent: "product" },
    { id: "twilio", label: "Twilio", parent: "product" },
    { id: "quo", label: "Quo / OpenPhone", parent: "product" },
    { id: "data", label: "Data & knowledge" },
    { id: "sql", label: "Advanced SQL", parent: "data" },
    { id: "knowledge-graphs", label: "Knowledge graphs", parent: "data" },
    { id: "search", label: "Search & retrieval", parent: "data" },
    { id: "postgres", label: "PostgreSQL", parent: "data" },
    { id: "pgvector", label: "pgvector", parent: "data" },
    { id: "devops", label: "DevOps" },
    { id: "observability", label: "Observability", parent: "devops" },
    { id: "betterstack", label: "Better Stack", parent: "devops" },
    { id: "sentry", label: "Sentry", parent: "devops" },
    { id: "datadog", label: "Datadog", parent: "devops" },
    { id: "opentelemetry", label: "OpenTelemetry", parent: "devops" },
    { id: "safety", label: "Security and safety", parent: "devops" },
    { id: "kubernetes", label: "Kubernetes", parent: "devops" },
    { id: "docker", label: "Docker", parent: "devops" },
    { id: "leadership", label: "Technical leadership", kind: "faq" },
    { id: "founder", label: "Founder/CTO", parent: "leadership", kind: "faq" },
    { id: "team-lead", label: "Team lead", parent: "leadership", kind: "faq" },
    { id: "games", label: "Gamedev" },
    { id: "desktop", label: "Desktop", parent: "games" },
    { id: "mobile", label: "Mobile (iOS/Android)", parent: "games" },
    { id: "unity", label: "Unity", parent: "games" },
    { id: "rendering", label: "Rendering", parent: "games" },
    { id: "multiplayer", label: "Multiplayer & netcode", parent: "games" },
  ],
  topicRelations: [
    { from: "evals", to: "braintrust" },
    { from: "pydantic-ai", to: "python" },
    { from: "livekit", to: "quo" },
    { from: "frontend", to: "react" },
    { from: "postgres", to: "pgvector" },
    { from: "devops", to: "kubernetes" },
    { from: "observability", to: "betterstack" },
    { from: "observability", to: "datadog" },
    { from: "observability", to: "opentelemetry" },
    { from: "observability", to: "braintrust" },
  ],
};
